# Generated by Django 4.2.3 on 2024-01-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
