# Generated by Django 4.2.3 on 2024-01-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('primary_check', 'Primary Check'), ('consultation', 'Consultation'), ('discharged', 'Discharged'), ('admitted', 'Admitted'), ('referred', 'Referred')], max_length=20)),
                ('medication_remarks', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.hospital')),
            ],
        ),
    ]
