# Generated by Django 4.2.3 on 2024-01-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='hname',
        ),
    ]
