# Generated by Django 5.0.1 on 2024-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_department_hospital_hospital_departments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='departments',
            new_name='department',
        ),
    ]
