# Generated by Django 4.2.3 on 2024-01-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_departments_hospital_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dname',
        ),
    ]
