# Generated by Django 4.2.3 on 2024-01-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_name_department_dname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medication_remarks',
        ),
    ]
