# Generated by Django 4.2.3 on 2024-01-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patient_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ph_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
