# Generated by Django 4.2.3 on 2024-01-10 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_dob_patient_ph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ph_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
