# Generated by Django 4.2.3 on 2024-01-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_history_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='time',
            new_name='date',
        ),
    ]
