# Generated by Django 5.0.1 on 2024-01-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_rename_time_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ph_number',
            field=models.CharField(default=8867142314, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ph_number',
            field=models.CharField(max_length=10),
        ),
    ]
